name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          check-latest: true
      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "TOKEN=${{secrets.SERVER_TOKEN}}" >> $GITHUB_ENV
          echo "UPLOAD_URL=${{secrets.UPLOAD_URL}}" >> $GITHUB_ENV
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install requirements
        run: pip install pyAesCrypt requests
      - name: Config version
        run: python config_version.py
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: build --no-build-cache
          gradle-version: wrapper
      - name: Compress and move artifact
        run: |
          cd build/libs
          zip minusbounce.zip *
          mv minusbounce.zip ../../
      - name: Upload artifact
        run: python upload_file.py release